# 测试配置文件
# @author sqyi
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai-basedquestionansweringapplicationplatformtables
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000